services:
  twilight_troop:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: "${myUID-1000}"
    command: ./start.sh
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    volumes:
      - ./data:/wd/data
      - ./bin:/wd/bin
      - ./obj:/wd/obj
      - ./src:/wd/src
